AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 99

Metrics/CyclomaticComplexity:
  Max: 32

Metrics/PerceivedComplexity:
  Max: 99

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/BlockNesting:
  Enabled: false
